import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Technology engineered around real decisions', description: 'SPENMER builds evidence-led products and technology services for complex operational work.' } },
  { path: 'autovision', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'AutoVision', description: 'Adaptive vehicle service intelligence for evidence-led decisions.' } },
  { path: 'service-profit-ai', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Service Profit', description: 'Identify and review evidence-supported service opportunities.' } },
  { path: 'for-dealers', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'For Dealers', description: 'A clearer view for dealership leadership and aftersales teams.' } },
  { path: 'business-value', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Business Value', description: 'Discuss measurable service opportunity and operational visibility.' } },
  { path: 'how-it-works', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'How It Works', description: 'From service signals to evidence-backed decisions.' } },
  { path: 'integration-security', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Integration and Security', description: 'DMS-neutral integration and trustworthy product boundaries.' } },
  { path: 'about', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'About SPENMER', description: 'The provisional SPENMER and AutoVision product relationship.' } },
  { path: 'products', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Products', description: 'Explore the AutoVision platform and its current commercial capability.' } },
  { path: 'services', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Technology Advisory & Engineering Services', description: 'Domain-aware advisory and engineering for products, platforms, and quality.' } },
  { path: 'contact', loadComponent: () => import('./contact-us.component').then(module => module.ContactUsComponent), data: { title: 'Contact Us', description: 'Start a conversation about AutoVision.' } },
  { path: 'contact/verify', loadComponent: () => import('./verify-contact.component').then(module => module.VerifyContactComponent), data: { title: 'Verify your email', description: 'Verify your commercial enquiry email.' } },
  { path: 'privacy', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Privacy', description: 'Privacy information will be published after legal review.' } },
  { path: 'terms', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Terms', description: 'Terms information will be published after legal review.' } },
  { path: 'request-demo', loadComponent: () => import('./request-demo.component').then(module => module.RequestDemoComponent), data: { title: 'Request a Demo', description: 'Request a guided AutoVision demonstration.' } },
  { path: '**', loadComponent: () => import('./page-shell.component').then(module => module.PageShellComponent), data: { title: 'Page not found', description: 'The requested page could not be found.', notFound: true } },
];