spring.application.name=autovision-platform

spring.jpa.open-in-view=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTOVISION_OIDC_ISSUER:http://localhost:8081/realms/autovision}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
