"""create sprint0 foundation tables

Revision ID: 9bca69d202bc
Revises: 
Create Date: 2026-08-12 22:36:26.699823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bca69d202bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('user_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refs_external_user_id'), 'user_refs', ['external_user_id'], unique=False)
    op.create_index('ix_user_refs_tenant_external_user_id', 'user_refs', ['tenant_id', 'external_user_id'], unique=True)
    op.create_index(op.f('ix_user_refs_tenant_id'), 'user_refs', ['tenant_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_class', sa.Enum('TWO_WHEELER', 'PASSENGER', 'LCV', 'TRUCK', 'BUS_COACH', 'HEAVY_SPECIAL', name='vehicle_class', create_constraint=True), nullable=False),
    sa.Column('powertrain', sa.Enum('ICE', 'HYBRID', 'EV', name='powertrain_type', create_constraint=True), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_powertrain'), 'vehicles', ['powertrain'], unique=False)
    op.create_index('ix_vehicles_tenant_canonical_id', 'vehicles', ['tenant_id', 'id'], unique=True)
    op.create_index('ix_vehicles_tenant_class', 'vehicles', ['tenant_id', 'vehicle_class'], unique=False)
    op.create_index(op.f('ix_vehicles_tenant_id'), 'vehicles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_class'), 'vehicles', ['vehicle_class'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('user_ref_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ref_id'], ['user_refs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_events_tenant_occurred_at', 'audit_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_user_ref_id'), 'audit_events', ['user_ref_id'], unique=False)
    op.create_index(op.f('ix_audit_events_vehicle_id'), 'audit_events', ['vehicle_id'], unique=False)
    op.create_index('ix_audit_events_vehicle_occurred_at', 'audit_events', ['vehicle_id', 'occurred_at'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_ref_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_ref_id'], ['user_refs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignments_role_name'), 'role_assignments', ['role_name'], unique=False)
    op.create_index(op.f('ix_role_assignments_tenant_id'), 'role_assignments', ['tenant_id'], unique=False)
    op.create_index('ix_role_assignments_tenant_user_role', 'role_assignments', ['tenant_id', 'user_ref_id', 'role_name'], unique=True)
    op.create_index(op.f('ix_role_assignments_user_ref_id'), 'role_assignments', ['user_ref_id'], unique=False)
    op.create_table('usage_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('engine_hours', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_level_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_snapshots_recorded_at'), 'usage_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_usage_snapshots_tenant_id'), 'usage_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_usage_snapshots_tenant_vehicle_recorded', 'usage_snapshots', ['tenant_id', 'vehicle_id', 'recorded_at'], unique=True)
    op.create_index(op.f('ix_usage_snapshots_vehicle_id'), 'usage_snapshots', ['vehicle_id'], unique=False)
    op.create_table('vehicle_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.String(length=80), nullable=False),
    sa.Column('identifier_value', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_identifiers_identifier_type'), 'vehicle_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_vehicle_identifiers_identifier_value'), 'vehicle_identifiers', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_vehicle_identifiers_tenant_id'), 'vehicle_identifiers', ['tenant_id'], unique=False)
    op.create_index('ix_vehicle_identifiers_tenant_type_value', 'vehicle_identifiers', ['tenant_id', 'identifier_type', 'identifier_value'], unique=True)
    op.create_index(op.f('ix_vehicle_identifiers_vehicle_id'), 'vehicle_identifiers', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_identifiers_vehicle_id'), table_name='vehicle_identifiers')
    op.drop_index('ix_vehicle_identifiers_tenant_type_value', table_name='vehicle_identifiers')
    op.drop_index(op.f('ix_vehicle_identifiers_tenant_id'), table_name='vehicle_identifiers')
    op.drop_index(op.f('ix_vehicle_identifiers_identifier_value'), table_name='vehicle_identifiers')
    op.drop_index(op.f('ix_vehicle_identifiers_identifier_type'), table_name='vehicle_identifiers')
    op.drop_table('vehicle_identifiers')
    op.drop_index(op.f('ix_usage_snapshots_vehicle_id'), table_name='usage_snapshots')
    op.drop_index('ix_usage_snapshots_tenant_vehicle_recorded', table_name='usage_snapshots')
    op.drop_index(op.f('ix_usage_snapshots_tenant_id'), table_name='usage_snapshots')
    op.drop_index(op.f('ix_usage_snapshots_recorded_at'), table_name='usage_snapshots')
    op.drop_table('usage_snapshots')
    op.drop_index(op.f('ix_role_assignments_user_ref_id'), table_name='role_assignments')
    op.drop_index('ix_role_assignments_tenant_user_role', table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_tenant_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_role_name'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index('ix_audit_events_vehicle_occurred_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_vehicle_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_user_ref_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_tenant_occurred_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_vehicles_vehicle_class'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_tenant_id'), table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_class', table_name='vehicles')
    op.drop_index('ix_vehicles_tenant_canonical_id', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_powertrain'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_user_refs_tenant_id'), table_name='user_refs')
    op.drop_index('ix_user_refs_tenant_external_user_id', table_name='user_refs')
    op.drop_index(op.f('ix_user_refs_external_user_id'), table_name='user_refs')
    op.drop_table('user_refs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
