package com.autovision.platform.intake;

public enum DatasetOperationalEventType {
    DATASET_RECEIVED,
    MATERIALIZATION_AUTHORIZED,
    REPLAY_REQUESTED,
    REPLAY_STARTED,
    REPLAY_SUCCEEDED,
    REPLAY_FAILED,
    ABANDONED_MATERIALIZATION_MARKED_FAILED,
    MANUAL_RECOVERY_REQUESTED
}
