package com.autovision.platform.intake;

public enum IntakeValidationCode {
    INTAKE_ENVELOPE_REQUIRED_FIELD,
    INTAKE_UNSUPPORTED_CONTRACT_VERSION,
    INTAKE_UNSUPPORTED_DELIVERY_TYPE,
    INTAKE_INVALID_RECORD_FILE,
    INTAKE_DUPLICATE_SOURCE_RECORD,
    INTAKE_REQUIRED_REFERENCE_MISSING,
    INTAKE_REFERENCE_NOT_FOUND,
    INTAKE_TENANT_CONTAINMENT_MISMATCH,
    INTAKE_DEALER_CONTAINMENT_MISMATCH,
    INTAKE_LOCATION_CONTAINMENT_MISMATCH,
    INTAKE_INVALID_DATE,
    INTAKE_INVALID_AMOUNT,
    INTAKE_INVALID_CURRENCY,
    INTAKE_OPTIONAL_FIELD_REVIEW
}